### ISSUE TITLE
stack trace when destination does not exist

### ISSUE THREAD

**Issue by Nr18** [Nr18/pull-request-codecommit#12]
**What were you trying to accomplish?**

Try to create a pull request when the configured destination does not exist in the remote repo.

## Expected Behavior
Expected a graceful error message

## Current Behavior
Raises an `IndexError`

## Possible Solution
Add error handling

## Steps to Reproduce (for bugs)

1. Create a remote with a `master` branch
2. Clone the repository and checkout `master`
3. Create a feature branch
4. Make sure that your config is set to `main`
5. Commit and execute `pull-request-codecommit`

## Environment

* **pull-request-codecommit version used**: 0.1.0
* **Debugging logs**

```python
Remote: codecommit::eu-west-1://my-profile@my-repo
Region: eu-west-1
Profile: my-profile
Repo: my-repo
Branch: feature/XXXXXX

fatal: ambiguous argument 'main..feature/XXXXXX': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/Users/xxxxx/.pyenv/versions/3.9.7/bin/pull-request-codecommit", line 8, in <module>
    sys.exit(main())
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jorisconijn/.pyenv/versions/3.9.7/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pull_request_codecommit/__init__.py", line 25, in main
    title, description = repo.pull_request_information()
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pull_request_codecommit/repository.py", line 88, in pull_request_information
    title = f"{commits.first.message.subject}{title_postfix}"
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pull_request_codecommit/git/commits.py", line 30, in first
    return self.__commits[0]
IndexError: list index out of range
```

**Comment by Nr18** [comment]
Fixed in [v0.2.0](https://github.com/Nr18/pull-request-codecommit/releases/tag/v0.2.0)
