### ISSUE TITLE
IndexError is raised when there are no commits

### ISSUE THREAD

**Issue by Nr18** [Nr18/pull-request-codecommit#8]
**What were you trying to accomplish?**

Executing the command while there are no changes.

## Expected Behavior
A graceful message that says that there are no changes.

## Current Behavior
IndexError is raised

## Possible Solution
Add error handling

## Steps to Reproduce (for bugs)

1. In main branch `git pull && git checkout -b fix/index-error`
2. Execute `pull-request-codecommit`

## Environment

* **pull-request-codecommit version used**: 0.1.0
* **Debugging logs**

```python
Remote: codecommit::eu-west-1://my-profile@my-repo
Region: eu-west-1
Profile: my-profile
Repo: my-repo
Branch: fix/index-error

Traceback (most recent call last):
  File "/Users/xxxxx/.pyenv/versions/3.9.7/bin/pull-request-codecommit", line 8, in <module>
    sys.exit(main())
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pull_request_codecommit/__init__.py", line 25, in main
    title, description = repo.pull_request_information()
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pull_request_codecommit/repository.py", line 88, in pull_request_information
    title = f"{commits.first.message.subject}{title_postfix}"
  File "/Users/xxxxx/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pull_request_codecommit/git/commits.py", line 30, in first
    return self.__commits[0]
IndexError: list index out of range
```

**Comment by Nr18** [comment]
Fixed in [v0.2.0](https://github.com/Nr18/pull-request-codecommit/releases/tag/v0.2.0)
